services:
  - type: web
    name: campus-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false   # set manually in Render dashboard
      - key: JWT_SECRET
        sync: false
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
      - key: TWILIO_SID
        sync: false
      - key: TWILIO_TOKEN
        sync: false
      - key: TWILIO_FROM
        sync: false
      - key: UPI_ID
        sync: false
      - key: UPI_NAME
        sync: false
      - key: QR_IMAGE_URL
        sync: false
      - key: APP_URL
        sync: false   # set to your Render URL e.g. https://campus-app.onrender.com
